background            #141414
foreground            #c7c0ad

cursor                #c49a53
cursor_text_color     #141414

selection_background  #465a66
selection_foreground  #e0d8c4

# base
color0                #141414
color8                #2a2d2d

# red
color1                #8f4b3e
color9                #b05d4b

# green
color2                #5f6954
color10               #78836c

# yellow / warning amber
color3                #c49a53
color11               #d7ac63

# blue / steel
color4                #465a66
color12               #5d7482

# magenta / rusted industrial purple
color5                #74606f
color13               #8a727f

# cyan / faded monitor glow
color6                #5e7a78
color14               #739694

# white / foreground
color7                #c7c0ad
color15               #e0d8c4

# UI accents
active_tab_foreground   #141414
active_tab_background   #c49a53

inactive_tab_foreground #8f8a7d
inactive_tab_background #1d1f1f

selection_foreground    #e0d8c4
